Merge 3.18.43 into android-3.18
Changes in 3.18.43:
	MIPS: KVM: Check for pfn noslot case
	ovl: fix workdir creation
	ARM: OMAP3: hwmod data: Add sysc information for DSI
	Revert "wext: Fix 32 bit iwpriv compatibility issue with 64 bit Kernel"
	bus: arm-ccn: Do not attempt to configure XPs for cycle counter
	bus: arm-ccn: Fix XP watchpoint settings bitmask
	ARM: kirkwood: ib62x0: fix size of u-boot environment partition
	ALSA: timer: fix division by zero after SNDRV_TIMER_IOCTL_CONTINUE
	ALSA: timer: fix NULL pointer dereference on memory allocation failure
	ALSA: usb-audio: Add sample rate inquiry quirk for B850V3 CP2114
	ARM: imx6: add missing BM_CLPCR_BYPASS_PMIC_READY setting for imx6sx
	ALSA: fireworks: accessing to user space outside spinlock
	iio: accel: kxsd9: Fix scaling bug
	sched/core: Fix a race between try_to_wake_up() and a woken up task
	usb: renesas_usbhs: fix clearing the {BRDY,BEMP}STS condition
	Btrfs: add missing blk_finish_plug in btrfs_sync_log()
	Btrfs: remove root_log_ctx from ctx list before btrfs_sync_log returns
	ipv6: addrconf: fix dev refcont leak when DAD failed
	crypto: cryptd - initialize child shash_desc on import
	powerpc/mm: Don't alias user region to other regions below PAGE_OFFSET
	xhci: fix null pointer dereference in stop command timeout function
	ALSA: timer: Call notifier in the same spinlock
	ALSA: timer: Fix zero-division by continue of uninitialized instance
	kvm-arm: Unmap shadow pagetables properly
	arm64: spinlocks: implement smp_mb__before_spinlock() as smp_mb()
	asm-generic: make copy_from_user() zero the destination properly
	USB: serial: simple: add support for another Infineon flashloader
	crypto: skcipher - Fix blkcipher walk OOM crash
	crypto: arm64/aes-ctr - fix NULL dereference in tail processing
	MIPS: paravirt: Fix undefined reference to smp_bootstrap
	genirq: Generic chip: Change irq_reg_{readl,writel} arguments
	genirq: Provide irq_gc_{lock_irqsave,unlock_irqrestore}() helpers
	MIPS: Add a missing ".set pop" in an early commit
	nl80211: validate number of probe response CSA counters
	asm-generic: {get,put}_user ptr argument evaluate only 1 time
	asm-generic: make get_user() clear the destination on errors
	frv: fix clear_user()
	hexagon: fix strncpy_from_user() error return
	ia64: copy_from_user() should zero the destination on access_ok() failure
	metag: copy_from_user() should zero the destination on access_ok() failure
	ARC: uaccess: get_user to zero out dest in cause of fault
	mips: copy_from_user() must zero the destination on access_ok() failure
	mn10300: failing __get_user() and get_user() should zero
	mn10300: copy_from_user() should zero on access_ok() failure...
	openrisc: fix copy_from_user()
	parisc: fix copy_from_user()
	ppc32: fix copy_from_user()
	s390: get_user() should zero on failure
	score: fix __get_user/get_user
	score: fix copy_from_user() and friends
	sh64: failing __get_user() should zero
	sh: fix copy_from_user()
	sparc32: fix copy_from_user()
	blackfin: fix copy_from_user()
	m32r: fix __get_user()
	microblaze: fix copy_from_user()
	microblaze: fix __get_user()
	avr32: fix copy_from_user()
	fix minor infoleak in get_user_ex()
	USB: change bInterval default to 10 ms
	can: flexcan: fix resume function
	ocfs2/dlm: fix race between convert and migration
	autofs races
	autofs: use dentry flags to block walks during expire
	fsnotify: add a way to stop queueing events on group shutdown
	fanotify: fix list corruption in fanotify_get_response()
	ocfs2: fix start offset to ocfs2_zero_range_for_truncate()
	fix fault_in_multipages_...() on architectures with no-op access_ok()
	btrfs: ensure that file descriptor used with subvol ioctls is a dir
	block: Do a full clone when splitting discard bios
	hexagon: Fix build failures in linux-next
	avr32: fix 'undefined reference to `___copy_from_user'
	ARM: orion: convert the irq_reg_{readl,writel} calls to the new API
	openrisc: fix the fix of copy_from_user()
	Linux 3.18.43

Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>

Conflicts:
	drivers/usb/serial/usb-serial-simple.c
	include/linux/irq.h

Change-Id: I6473b26b5d02b381f0c26b9eb7bb78ba126d7f86